Syncing new test vectors and base mode
novifinancial/voprf pull request #58
Opened 2022-02-03 23:09 UTC by kevinlewi

To sync with version 09 of voprf. This version introduces a new mode (so we have three now: base, verifiable, and "poprf").

2022-02-03 23:11 UTC, kevinlewi commented
@daxpedda : In the latest version, only the "POPRF" mode uses the "PreparedTScalar" and will follow the batch_evaluate_prepare -> batch_evaluate_finish paradigm.

However, the new "Verifiable" mode no longer needs to create a PreparedTScalar, and can just have a single function execute the batch_evaluate, I believe. I was hoping to make this change, but was struggling to make sense of some of the types that were introduced here. Happy to sync off-line if you get a chance and I can explain further where I got stuck!

2022-02-04 14:18 UTC, daxpedda commented
Will take a look soon'ish!

2022-02-04 22:32 UTC, daxpedda requested changes
LGTM.

Things I will do tmrw:
- Actually go check with the spec, I only reviewed how the code looks.
- Fix `batch_evaluate`. Will make a PR against this branch.

2022-02-04 22:32 UTC, daxpedda commented on src/voprf.rs
> +        if counter > 255 {
This is probably better in a `for counter in 0..=255` loop.

2022-02-04 22:32 UTC, daxpedda commented on src/voprf.rs
> +        let counter_i2osp = i2osp_1(counter).map_err(|_| Error::DeriveKeyPair)?;
If we let `counter` be a `u8`, we can simply use `.to_be_bytes()` here, which also can't fail.

2022-02-04 22:32 UTC, daxpedda commented on src/voprf.rs
> +        &GenericArray::from(STR_CHALLENGE),
We don't need to use `GenericArray` here, this is already a byte slice.

2022-02-04 22:32 UTC, daxpedda commented on src/voprf.rs
> +        .zip(iter::repeat(finalize_dst))
Now that `finalize_dst` is "free" we won't need to pass it through here either.

2022-02-04 22:32 UTC, daxpedda commented on src/voprf.rs
> +    let finalize_dst = GenericArray::from(STR_FINALIZE);
As above, `STR_FINALIZE` is already a byte slice.

2022-02-04 22:32 UTC, daxpedda commented on src/voprf.rs
> +            &GenericArray::from(STR_COMPOSITE),
As above.

2022-02-05 21:43 UTC, kevinlewi commented
Thanks for leaving the comments! I have not addressed them just yet (am adding POPRF in first), and could use your eyes on that first...!

2022-02-08 11:23 UTC, kevinlewi commented
As of the latest commit on this branch, the implementation should be in sync with the CFRG's test vectors for all three modes (OPRF, VOPRF, POPRF). I split up the previous "voprf.rs" into three files, one for each mode. However, I removed the no-alloc versions since I could not get them to compile. I believe the no-alloc version is only needed for the batch functions of POPRF, but not VOPRF.

Would be great if you could help here @daxpedda !

Also, the doctests do not currently pass, and many docs for functions need to be updated. Will be happy to do so once we have the no-alloc version working!

2022-02-12 04:49 UTC, daxpedda commented
I addressed the remaining concerns in #59.

2022-02-13 11:50 UTC, kevinlewi commented
Merging along with #59

2022-02-13 11:50 UTC, merged